global using System.Text.Json;
global using System.Text;
global using Azure.Storage.Blobs;
global using Application.ObjectStorage;
global using Infrastructure.HttpClients;
global using Infrastructure.JsonSerialization;
global using EnBref.Application.Models;
global using EnBref.Infrastructure.LocalStorage;
global using EnBref.Infrastructure.GithubCdn.Models;